/*

 ARGH.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 31 to 34

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define ArghSkinNameBank 0
/* Start of tile array. */
extern unsigned char ArghSkinName[];

/* End of ARGH.H */
